Repository j-yesung/magic-pos, pull requests merged in 2024-02, with the labels that each got.

#449 ✨ update: react-hook-form 적용 (#448)
  package.json
  src/components/auth/element/SignCaption.tsx
  src/components/auth/form/FindPassword.tsx
  src/components/auth/form/Input.tsx
  src/components/auth/form/Login.tsx
  src/components/auth/form/ResetPassword.tsx
  src/components/auth/form/Signup.tsx
  src/components/auth/form/SignupSuccess.tsx
  src/components/auth/styles/Auth.module.css
  src/components/common/Button.tsx
  src/data/inputData.ts
  src/pages/auth/findPassword.tsx
  src/pages/auth/login.tsx
  src/pages/auth/reset.tsx
  src/pages/auth/signup.tsx
  src/pages/auth/success.tsx
  src/server/api/external/business.ts
  src/types/user.d.ts
  yarn.lock
Labels: ✨ 기능 개발, 📝 기능 수정, 🪚 리팩토링

#453 ♻️ refactoring : moment->dayjs로 교체, 메뉴 등록폼 리팩토링
  src/components/menu-category/styles/category.module.css
  src/components/menu-item/items/form/FormItem.tsx
  src/components/menu-item/items/form/RemoveItem.tsx
  src/components/menu-item/styles/menu-item-card.module.css
  src/hooks/menu/menu-item/useSetMenuItems.ts
  src/hooks/menu/menu-item/useSetMenuOption.ts
Labels: 🪚 리팩토링

#458 ✨ update: form으로 인한 코드 이전 (#457) (#450)
  backup/AuthForm.tsx
  backup/Input.tsx
  backup/User.tsx
  backup/auth.ts
  backup/button/FormButton.tsx
  backup/input-props.ts
  src/components/auth/form/FindPassword.tsx
  src/components/auth/form/Login.tsx
  src/components/auth/form/ResetPassword.tsx
  src/components/auth/form/Signup.tsx
  src/components/common/Input.tsx
  src/components/store/StoreMain.tsx
  src/components/store/styles/StoreContents.module.css
  src/components/store/sub-component/ConfirmTable.tsx
  src/components/store/sub-component/StoreInfo.tsx
  src/components/store/sub-component/StoreSetButton.tsx
  src/components/store/sub-component/StoreTimeSet.tsx
  src/data/input-props.ts
  src/data/inputData.ts
Labels: 📝 기능 수정, 🪚 리팩토링

#473 🚚 move: hooks 작업 중 (#286)
  src/components/menu-category/container/card/Card.tsx
  src/components/menu-category/container/form/FormCategory.tsx
  src/components/menu-category/container/form/RemoveCategory.tsx
  src/components/menu-item/items/card/Card.tsx
  src/components/menu-item/items/form/FormItem.tsx
  src/hooks/service/menu/useDragDrop.ts
  src/hooks/service/menu/useOptionFiltering.ts
Labels: 🪚 리팩토링

#486 ✨ update: 스크롤 진행 상태 상단바 구현
  src/components/layout/home/HomeLayout.tsx
  src/components/layout/home/main/animation/ProgressBar.tsx
  src/components/layout/home/styles/Home.module.css
Labels: ✨ 기능 개발
