Repository j-yesung/magic-pos, pull requests merged in 2024-01, with the labels that each got.

#24 Feat/menu/category 메뉴 카테고리 기능 (#8)
  src/components/menu-category/Categories.tsx
  src/components/menu-category/Category.tsx
  src/components/menu-category/Form.tsx
  src/components/menu-category/styles/categories.module.css
  src/components/menu-category/styles/category.module.css
  src/components/menu-category/styles/form.module.css
  src/pages/api/menu-category.ts
  src/pages/menu-category/index.tsx
  src/shared/store/menu-category.ts
  src/styles/globals.css
  src/types/menu-category.d.ts
Labels: ✨ 기능 개발

#72 Feat/menu/item 메뉴 아이템
  src/components/layout/admin/AdminLayout.tsx
  src/components/menu-item/MenuItem.tsx
  src/components/menu-item/MenuItemCard.tsx
  src/components/menu-item/MenuItemCategory.tsx
  src/components/menu-item/MenuItemContainer.tsx
  src/components/menu-item/MenuItemForm.tsx
  src/components/menu-item/MenuItemList.tsx
  src/components/menu-item/styles/menu-item-card.module.css
  src/components/menu-item/styles/menu-item-category.module.css
  src/components/menu-item/styles/menu-item-container.module.css
  src/components/menu-item/styles/menu-item-form.module.css
  src/components/menu-item/styles/menu-item-list.module.css
  src/components/menu-item/styles/menu-item.module.css
  src/pages/admin/menu-item/index.tsx
  src/server/api/supabase/menu-category.ts
  src/server/api/supabase/menu-item.ts
  src/shared/store/menu-item.ts
  src/styles/globals.css
Labels: ✨ 기능 개발, 🖼️ 레이아웃

#80 [1차 병합] 어드민-가게 설정 (#73)
  src/components/auth/AuthForm.tsx
  src/components/auth/Input.tsx
  src/components/layout/admin/AdminLayout.tsx
  src/components/store/StoreContents.tsx
  src/hooks/auth/useAuth.ts
  src/hooks/auth/useInput.ts
  src/hooks/store/useGetQuery.ts
  src/hooks/store/useStoreQuery.ts
  src/pages/admin/store.tsx
  src/server/api/supabase/auth.ts
  src/server/api/supabase/store.ts
  src/shared/store/auth.ts
  src/types/common.d.ts
Labels: ✨ 기능 개발, 🖼️ 레이아웃

#90 로그인 & 회원가입 레이아웃 및 유효성 검사 (#10)
  src/components/auth/AuthForm.tsx
  src/components/auth/Input.tsx
  src/components/auth/User.tsx
  src/components/auth/styles/Auth.module.css
  src/components/layout/home/styles/StickBar.module.css
  src/hooks/auth/useAuth.ts
  src/hooks/auth/useValid.ts
  src/server/api/external/business.ts
  yarn.lock
Labels: 📝 기능 수정, 🎨 디자인 수정

#95 홈 페이지 - Top 버튼 (#47)
  package.json
  src/components/layout/home/main/ScrollTop.tsx
  src/components/layout/home/main/StickBar.tsx
  src/components/layout/home/styles/StickBar.module.css
  yarn.lock
Labels: ✨ 기능 개발, 🎨 디자인 수정

#96 컴포넌트 다중 렌더링 버그 수정
  src/components/auth/Input.tsx
  src/data/input-props.ts
  src/hooks/auth/useErrorMessage.ts
  src/hooks/auth/useValid.ts
  src/server/api/supabase/auth.ts
Labels: 🐛 버그

#98 Feat/management
  src/components/management/Management.tsx
  src/components/management/managementModal/ManagementModal.tsx
  src/components/management/managementModal/styles/ManagementModal.module.css
  src/components/management/managementSideBar/SideBarButtonBox.tsx
  src/components/management/qrCodeModal/QrCodeModal.tsx
  src/components/management/qrCodeModal/packagingQrCodeContainer/PackagingQrCodeContainer.tsx
  src/components/management/qrCodeModal/qrCodelistItem/QrCodeListItem.tsx
  src/components/management/qrCodeModal/qrCodelistItem/styles/QrCodeListitem.module.css
  src/components/management/qrCodeModal/shopQrCodeContainer/ShopQrCodeContainer.tsx
  src/components/management/qrCodeModal/styles/QrCodeModal.module.css
  src/hooks/management/useQRCodeDownLoad.ts
  src/shared/store/management.ts
  src/styles/globals.css
Labels: ✨ 기능 개발

#101 어드민 메뉴 옵션 등록 옵션 작업
  src/components/menu-item/MenuItem.tsx
  src/components/menu-item/MenuItemCard.tsx
  src/components/menu-item/MenuItemContainer.tsx
  src/components/menu-item/MenuItemForm.tsx
  src/components/menu-item/MenuItemFormButton.tsx
  src/components/menu-item/MenuItemFormInput.tsx
  src/components/menu-item/MenuItemFormOption.tsx
  src/components/menu-item/MenuOptionModal.tsx
  src/components/menu-item/MenuOptionModalButton.tsx
  src/components/menu-item/MenuOptionModalInput.tsx
  src/components/menu-item/styles/menu-item-card.module.css
  src/components/menu-item/styles/menu-item-form.module.css
  src/components/menu-item/styles/menu-option-modal.module.css
  src/pages/admin/menu-item/index.tsx
  src/server/api/supabase/menu-item.ts
  src/shared/store/menu-item.ts
Labels: ✨ 기능 개발

#106 관리자 페이지 사이드 바 (#103)
  public/icons/Ellipse.svg
  public/icons/close.svg
  public/icons/hamburger.svg
  src/components/layout/admin/AdminLayout.tsx
  src/components/layout/admin/header/HamburgerMenu.tsx
  src/components/layout/admin/header/Header.tsx
  src/components/layout/admin/header/HeaderToggleButton.tsx
  src/components/layout/admin/nav/NavBar.tsx
  src/components/layout/admin/styles/AdminLayout.module.css
  src/components/store/styles/StroeContents.module.css
  src/shared/store/sidebar.ts
Labels: ✨ 기능 개발, 🖼️ 레이아웃

#111 메뉴 아이템 swiper css 추가
  src/components/menu-item/MenuItemCard.tsx
  src/components/menu-item/MenuItemCategory.tsx
  src/components/menu-item/MenuItemFormButton.tsx
  src/components/menu-item/MenuOptionModalInput.tsx
  src/components/menu-item/styles/menu-item-card.module.css
  src/components/menu-item/styles/menu-item-category.module.css
  src/components/menu-item/styles/menu-item-form.module.css
  src/components/menu-item/styles/menu-item-list.module.css
  src/components/menu-item/styles/menu-item.module.css
  src/pages/admin/menu-item/index.tsx
Labels: 🎨 디자인 수정

#112 side bar in development
  src/components/layout/admin/AdminLayout.tsx
  src/components/layout/admin/header/HeaderToggleButton.tsx
  src/components/layout/admin/nav/Sidebar.tsx
  src/components/layout/admin/nav/SidebarList.tsx
  src/components/layout/admin/styles/AdminLayout.module.css
  src/data/admin.ts
  src/shared/store/sidebar.ts
  src/shared/store/toggle.ts
Labels: 📝 기능 수정, 🖼️ 레이아웃

#116 사이드 바 수정 (#103)
  src/components/layout/admin/nav/Sidebar.tsx
  src/components/layout/admin/styles/AdminLayout.module.css
Labels: 📝 기능 수정, 🎨 디자인 수정

#117 Fix/syntax
  src/components/auth/User.tsx
  src/components/layout/admin/AdminLayout.tsx
  src/components/layout/home/main/StartButton.tsx
  src/components/layout/home/main/StickBar.tsx
  src/components/management/Management.tsx
  src/data/auth.ts
Labels: 🪚 리팩토링

#127 회원 인증 관련 폼 버튼 리팩토링 (#10)
  src/components/auth/AuthForm.tsx
  src/components/auth/button/FormButton.tsx
  src/components/auth/styles/Auth.module.css
  src/data/auth.ts
  src/server/api/supabase/auth.ts
Labels: 🪚 리팩토링

#131 ♻️ refactor: 카테고리, 아이템 리팩토링 작업중..
  src/components/menu-category/Categories.tsx
  src/components/menu-category/Category.tsx
  src/components/menu-category/Form.tsx
  src/components/menu-item/MenuItemContainer.tsx
  src/hooks/menu-category/useFetchCategories.ts
  src/hooks/menu-category/useSetCategories.ts
  src/hooks/menu-item/useCategoryWithMenu.ts
  src/hooks/menu-item/useMenuOptions.ts
  src/hooks/menu/useCategories.ts
  src/server/api/supabase/menu-category.ts
  src/shared/store/menu-category.ts
  src/types/menu-category.d.ts
Labels: 🪚 리팩토링

#132 :bug: bugfix: 버그 수정 (#30)
  src/components/order/receipt/ReceiptContainer.tsx
  src/components/order/success/SuccessContainer.tsx
  src/hooks/order/useNumberOrderFetchQuery.ts
  src/hooks/order/useNumberOrderQuery.ts
  src/hooks/order/useNumberOrderSetQuery.ts
  src/hooks/order/useStoreOrderFetchQuery.ts
  src/hooks/order/useStoreOrderQuery.ts
  src/hooks/order/useStoreOrderSetQuery.ts
  src/pages/order/[storeId].tsx
  src/server/api/supabase/order-store.ts
  src/server/api/supabase/order-togo.ts
Labels: 🐛 버그

#135 Feat/management
  next.config.js
  public/audio/DingSoundEffect.mp3
  src/components/management/Management.tsx
  src/components/management/managementContainer/ShopListItem.tsx
  src/components/management/styles/Management.module.css
  src/hooks/toast/useToast.ts
  src/server/api/supabase/management.ts
Labels: ✨ 기능 개발

#140 🐛 bugfix: 버그 경로 에러 수정
  src/components/menu-item/MenuItemContainer.tsx
Labels: 🐛 버그

#141 🩹 fix: Change from auth page to modal & toast (#10)
  src/components/auth/styles/Auth.module.css
  src/hooks/auth/useAuth.ts
  src/server/api/supabase/auth.ts
Labels: 📝 기능 수정

#144 :sparkles: top-center 추가 (#75)
  src/components/toast/Toast.tsx
  src/components/toast/styles/Toast.module.css
  src/hooks/toast/useToast.ts
  src/types/common.d.ts
Labels: ✨ 기능 개발

#145 💄 style: 오른쪽 사이드 입력창 공통 컴포넌트 작업 (#138)
  src/components/layout/admin/SideFormLayout.tsx
  src/components/layout/admin/styles/SideFormLayout.module.css
  src/components/menu-category/Category.tsx
  src/components/menu-category/Form.tsx
  src/components/menu-category/styles/category.module.css
  src/components/menu-category/styles/form.module.css
  src/components/menu-item/MenuItem.tsx
  src/components/menu-item/MenuItemCard.tsx
  src/components/menu-item/MenuItemCategory.tsx
  src/components/menu-item/MenuItemForm.tsx
  src/components/menu-item/MenuItemFormButton.tsx
  src/components/menu-item/MenuItemFormInput.tsx
  src/components/menu-item/MenuOptionModalButton.tsx
  src/components/menu-item/MenuOptionModalInput.tsx
  src/components/menu-item/styles/menu-item-card.module.css
  src/components/menu-item/styles/menu-item-container.module.css
  src/components/menu-item/styles/menu-item-form.module.css
  src/components/menu-item/styles/menu-item.module.css
  src/components/menu-item/styles/menu-option-modal.module.css
  src/shared/store/side-form.ts
  src/styles/reset.css
Labels: 🎨 디자인 수정

#160 🩹 fix: 사이드 바 페이지 동적 이동 로직 수정 (#103)
  src/components/layout/admin/nav/Sidebar.tsx
Labels: 📝 기능 수정

#164 QA: 로그인 & 회원가입 수정 (#150) (#151)
  src/components/auth/AuthForm.tsx
  src/components/auth/Input.tsx
  src/components/auth/button/FormButton.tsx
  src/components/common/Button.tsx
  src/components/layout/home/main/StartButton.tsx
  src/data/input-props.ts
  src/hooks/auth/useAuth.ts
  src/hooks/auth/useErrorMessage.ts
Labels: 📝 기능 수정

#165 QA: 메뉴 아이템 에러 수정 (#157)
  src/components/layout/admin/SideFormLayout.tsx
  src/components/menu-category/Form.tsx
  src/components/menu-item/MenuItem.tsx
  src/components/menu-item/MenuItemContainer.tsx
  src/components/menu-item/MenuItemFormInput.tsx
  src/components/menu-item/MenuOptionModalInput.tsx
  src/components/menu-item/styles/menu-item-container.module.css
  src/components/menu-item/styles/menu-option-modal.module.css
Labels: 🤔 QA

#174 메뉴 아이템, 카테고리 훅 분리(#146)
  src/components/menu-category/Categories.tsx
  src/components/menu-category/Category.tsx
  src/components/menu-category/Form.tsx
  src/components/menu-item/MenuItemContainer.tsx
  src/components/menu-item/MenuItemFormButton.tsx
  src/components/menu-item/items/MenuItem.tsx
  src/components/menu-item/items/MenuItemCard.tsx
  src/components/menu-item/items/MenuItemCategory.tsx
  src/components/menu-item/items/MenuItemForm.tsx
  src/components/menu-item/items/MenuItemFormButton.tsx
  src/components/menu-item/items/MenuItemFormInput.tsx
  src/components/menu-item/items/MenuItemList.tsx
  src/components/menu-item/options/MenuItemFormOption.tsx
  src/components/menu-item/options/MenuOptionModal.tsx
  src/components/menu-item/options/MenuOptionModalButton.tsx
  src/components/menu-item/options/MenuOptionModalInput.tsx
  src/components/table/Table.tsx
  src/hooks/menu/menu-category/useFetchCategories.ts
  src/hooks/menu/menu-category/useSetCategories.ts
  src/hooks/menu/menu-item/useFetchMenuItems.ts
  src/hooks/menu/menu-item/useFetchMenuOption.ts
  src/hooks/menu/menu-item/useFetchMenuOptionDetail.ts
  src/hooks/menu/menu-item/useSetMenuItems.ts
  src/hooks/menu/menu-item/useSetMenuOption.ts
  src/hooks/menu/menu-item/useSetMenuOptionDetail.ts
  src/server/api/supabase/menu-category.ts
  src/server/api/supabase/menu-item.ts
  src/shared/store/menu-category.ts
  src/shared/store/menu-item.ts
Labels: 🪚 리팩토링

#176 :lipstick: style: Modal Confirm 스타일 수정
  src/components/modal/default/ConfirmModal.tsx
  src/components/modal/default/styles/ConfirmModal.module.css
  src/components/modal/styles/Modal.module.css
Labels: 🎨 디자인 수정

#179 관리자 제목 동적 생성 및 아이콘 추가 (#178)
  src/components/layout/admin/main/CategoryTitle.tsx
  src/components/layout/admin/main/CategoryTitleIcon.tsx
  src/components/layout/admin/nav/Sidebar.tsx
  src/components/layout/admin/styles/AdminLayout.module.css
Labels: ✨ 기능 개발, 🖼️ 레이아웃

#181 ♻️ refactor: 유저 정보 세션 상태 액션, 스토어 분리 (#180)
  src/components/auth/User.tsx
  src/components/layout/admin/AdminLayout.tsx
  src/components/layout/admin/main/CategoryTitle.tsx
  src/components/layout/home/main/StartButton.tsx
  src/components/layout/home/main/StickBar.tsx
  src/components/management/Management.tsx
  src/components/menu-category/Categories.tsx
  src/components/menu-item/MenuItemContainer.tsx
  src/components/order-check-list/OrderCheckListContentList.tsx
  src/components/platform/container/PlatFormWrapper.tsx
  src/components/store/StoreContents.tsx
  src/hooks/auth/useAuth.ts
  src/shared/store/auth.ts
  src/shared/store/session.ts
Labels: 🪚 리팩토링

#187 🩹 fix: 가게 설정 틀 잡고 셀렉트 박스 포맷 변경 (#186)
  src/components/auth/Input.tsx
  src/components/auth/styles/Auth.module.css
  src/components/store/StoreContents.tsx
  src/components/store/StoreTimeSet.tsx
  src/components/store/styles/StroeContents.module.css
  src/data/input-props.ts
Labels: 📝 기능 수정, 🖼️ 레이아웃

#193 ✨ update: 영업시간 설정 셀렉트 컴포넌트 생성 (#186)
  package.json
  src/components/store/StoreMain.tsx
  src/components/store/StoreTimeSet.tsx
  src/components/store/styles/StroeContents.module.css
  src/components/store/sub-component/StoreSelectBox.tsx
  src/components/store/sub-component/StoreSetButton.tsx
  src/components/store/sub-component/StoreTimeSet.tsx
  src/components/utils/time-format.ts
  src/hooks/store/useStoreQuery.ts
  src/pages/admin/store.tsx
  src/types/admin-store.d.ts
  yarn.lock
Labels: ✨ 기능 개발

#198 :ambulance: hotfix: 모달 중복 열림 안됨 수정
  src/components/modal/Modal.tsx
  src/components/modal/styles/Modal.module.css
Labels: 🐛 버그

#199 Design/auth
  src/components/auth/AuthForm.tsx
  src/components/auth/Input.tsx
  src/components/auth/styles/Auth.module.css
  src/hooks/auth/useErrorMessage.ts
Labels: 📝 기능 수정, 🎨 디자인 수정

#206 :lipstick: style: 주문 내역 확인 페이지 css 수정
  src/components/order-check-list/OrderCheckListItem.tsx
  src/components/order-check-list/styles/OrderCheckListItem.module.css
Labels: 🎨 디자인 수정

#208 🩹 fix: 모달 레이아웃 & 버튼 별 분기처리 (#205)
  src/components/management/qrCodeModal/QrCodeModal.tsx
  src/components/management/qrCodeModal/packagingQrCodeContainer/PackagingQrCodeContainer.tsx
  src/components/management/qrCodeModal/qrCodelistItem/styles/QrCodeListitem.module.css
  src/components/management/qrCodeModal/shopQrCodeContainer/ShopQrCodeContainer.tsx
  src/components/management/qrCodeModal/styles/QrCodeModal.module.css
Labels: 📝 기능 수정, 🖼️ 레이아웃

#230 ✨ update: 이메일 중복 체크 (#10)
  src/components/auth/AuthForm.tsx
  src/hooks/auth/useAuth.ts
  src/server/api/supabase/auth.ts
Labels: ✨ 기능 개발

#241 ✨ update: 엔터 시, 로그인 로직 구현 (#10)
  src/components/auth/AuthForm.tsx
  src/components/auth/Input.tsx
Labels: ✨ 기능 개발

#253 관리자 페이지 - 가게 설정 테이블 사용 여부
  src/components/store/StoreMain.tsx
  src/components/store/styles/StroeContents.module.css
  src/components/store/sub-component/ConfirmTable.tsx
  src/components/store/sub-component/StoreSelectBox.tsx
  src/components/store/sub-component/StoreTimeSet.tsx
  src/hooks/store/useStoreQuery.ts
  src/server/api/supabase/store.ts
  src/types/admin-store.d.ts
Labels: ✨ 기능 개발

#256 Toast UI 디자인
  src/components/toast/ToastContent.tsx
  src/components/toast/styles/Toast.module.css
  src/hooks/toast/useToast.ts
  src/types/common.d.ts
Labels: 🎨 디자인 수정

#268 언어 선택 기능 개발
  package.json
  src/components/kiosk/order-type/LanguageList.tsx
  src/components/kiosk/order-type/OrderTypeCard.tsx
  src/components/kiosk/order-type/OrderTypeContainer.tsx
  src/components/kiosk/order-type/styles/LanguageList.module.css
  src/components/kiosk/order-type/styles/OrderTypeContainer.module.css
  src/pages/_app.tsx
  src/shared/i18n.ts
  yarn.lock
Labels: ✨ 기능 개발

#270 🩹 fix: 테이블 사용 여부 DB 상태 변경 로직 개선 (#248)
  src/components/layout/admin/nav/SidebarList.tsx
  src/components/store/sub-component/ConfirmTable.tsx
  src/shared/store/table.ts
Labels: 📝 기능 수정

#275 ✨ update: 문의하기 메일 전송 기능 구현 (#271)
  src/components/layout/admin/nav/SendMail.tsx
  src/components/layout/admin/nav/Sidebar.tsx
  src/components/layout/admin/styles/SendMail.module.css
  src/hooks/service/useSendEmail.ts
Labels: ✨ 기능 개발, 🖼️ 레이아웃

#295 메인 페이지 작업 v1.0
  package.json
  public/images/iphone.svg
  src/components/layout/home/HomeLayout.tsx
  src/components/layout/home/main/Contents.tsx
  src/components/layout/home/main/Slider.tsx
  src/components/layout/home/main/WateMark.tsx
  src/components/layout/home/main/animation/TransitionText.tsx
  src/components/layout/home/main/section/KioskField.tsx
  src/components/layout/home/main/section/KioskVideo.tsx
  src/components/layout/home/module-export.ts
  src/components/layout/home/styles/Home.module.css
  src/components/layout/home/styles/Section.module.css
  src/data/scroll-props.ts
  yarn.lock
Labels: ✨ 기능 개발, 🖼️ 레이아웃

#296 :pencil2: fix: 추천메뉴 수정 (#293)
  public/locales/en/translation.json
  public/locales/ja/translation.json
  public/locales/ko/translation.json
  public/locales/zh/translation.json
  src/server/service/translate.ts
  src/utils/kiosk-helper.ts
Labels: 📝 기능 수정

#311 🔧 config: PWA 설정 (#310)
  next.config.js
  package.json
  yarn.lock
Labels: ⚙️ 설정

#317 Bugfix/kiosk
  src/components/kiosk/payment/PaymentContainer.tsx
  src/components/kiosk/receipt/ReceiptContainer.tsx
  src/components/kiosk/receipt/ReceiptOrderHeader.tsx
  src/components/layout/order/footer/StepButton.tsx
  src/shared/store/kiosk.ts
Labels: 🐛 버그, ✨ 기능 개발

#319 ♻️ refactor: 메뉴 옵션 디테일 디자인과 같게 수정 (#286)
  src/components/menu-category/Categories.tsx
  src/components/menu-category/Category.tsx
  src/components/menu-category/CategroyCard.tsx
  src/components/menu-category/Form.tsx
  src/components/menu-category/modal/MenuCategoryModal.tsx
  src/components/menu-item/MenuItemContainer.tsx
  src/components/menu-item/items/MenuItem.tsx
  src/components/menu-item/items/MenuItemCard.tsx
  src/components/menu-item/items/MenuItemCategory.tsx
  src/components/menu-item/items/MenuItemForm.tsx
  src/components/menu-item/items/MenuItemFormButton.tsx
  src/components/menu-item/items/MenuItemFormInput.tsx
  src/components/menu-item/items/MenuItemModal.tsx
  src/components/menu-item/options/MenuItemFormOption.tsx
  src/components/menu-item/options/MenuOptionModalButton.tsx
  src/components/menu-item/options/MenuOptionModalInput.tsx
  src/components/menu-item/styles/menu-option-modal.module.css
  src/shared/store/menu-category.ts
  src/shared/store/menu-item.ts
  src/shared/store/menu/menu-category.ts
  src/shared/store/menu/menu-item.ts
  src/shared/store/menu/menu-option.ts
Labels: 📝 기능 수정

#325 ✨ update: 주문별 토큰 값 조회 (#310)
  src/server/api/supabase/user-token.ts
Labels: ✨ 기능 개발

#324 💄 style: 메뉴 카테고리, 아이템 태블릿 사이즈까지 반응형 작업 (#286)
  src/components/menu-category/styles/category.module.css
  src/components/menu-item/items/MenuItemCard.tsx
  src/components/menu-item/styles/menu-item-card.module.css
  src/components/menu-item/styles/menu-item-form.module.css
Labels: 🎨 디자인 수정

#331 🩹 fix: 메뉴 사진 등록 후 이미지만 삭제 가능하게
  public/images/menu_samle.png
  src/components/menu-item/items/MenuItem.tsx
  src/components/menu-item/items/MenuItemForm.tsx
  src/components/menu-item/items/MenuItemFormButton.tsx
  src/components/menu-item/items/MenuItemFormInput.tsx
  src/components/menu-item/styles/menu-item-card.module.css
  src/components/menu-item/styles/menu-item-form.module.css
  src/hooks/menu/menu-item/useSetMenuItems.ts
  src/server/api/supabase/menu-item.ts
  src/shared/store/menu/menu-item.ts
Labels: 📝 기능 수정

#337 🩹 fix: 이미지 삭제 안되는 부분 코드 수정 (#286)
  src/components/menu-item/items/MenuItemForm.tsx
  src/components/menu-item/options/MenuOptionModalButton.tsx
  src/components/menu-item/styles/menu-item-card.module.css
  src/components/menu-item/styles/menu-item-form.module.css
Labels: 📝 기능 수정

#364 🩹 fix: 관리자 페이지 레이아웃 및 기능 수정 (#271) (#245) (#363)
  src/components/layout/admin/header/HeaderToggleButton.tsx
  src/components/layout/admin/nav/SendMail.tsx
  src/components/layout/admin/nav/Sidebar.tsx
  src/components/layout/admin/styles/AdminLayout.module.css
  src/components/layout/admin/styles/SendMail.module.css
  src/components/store/styles/StroeContents.module.css
Labels: 📝 기능 수정, 🎨 디자인 수정, 🖼️ 레이아웃

#365 🩹 fix: 로그인 이메일 저장 수정 & 회원가입 성공 3D 아이콘 수정 (#362)
  public/icons/success.svg
  src/components/auth/AuthForm.tsx
  src/components/auth/element/SignCaption.tsx
  src/components/auth/styles/Auth.module.css
  src/shared/store/toggle.ts
Labels: 📝 기능 수정, 🎨 디자인 수정

#383 :bug: bugfix: 토큰을 발급받을 수 없는 경우 주문 완료 되지 않음
  src/components/kiosk/success/SuccessContainer.tsx
  src/components/management/managementSideBar/OrderItem.tsx
Labels: 🐛 버그

#386 :bug: 메뉴 두번 출력 현상 수정 (#385)
  src/components/kiosk/index/QrReaderContainer.tsx
  src/components/kiosk/receipt/ReceiptContainer.tsx
  src/hooks/query/order/useNumberOrderFetchQuery.ts
  src/hooks/query/order/useStoreOrderFetchQuery.ts
  src/shared/store/kiosk.ts
Labels: 🐛 버그

#390 🩹 fix: 메뉴 아이템 수정 (#286)
  public/icons/exclamation-mark.svg
  src/components/menu-category/Category.tsx
  src/components/menu-category/styles/category.module.css
  src/components/menu-item/MenuItemContainer.tsx
  src/components/menu-item/items/MenuItemCategory.tsx
  src/components/menu-item/items/MenuItemForm.tsx
  src/components/menu-item/styles/menu-item-card.module.css
  src/components/menu-item/styles/menu-item-category.module.css
  src/components/menu-item/styles/menu-item-container.module.css
  src/hooks/menu/menu-item/useFetchMenuItems.ts
Labels: 🐛 버그

#402 🐛 bugfix: 메인 & 관리자 버그 수정 (#400)
  src/components/layout/admin/header/HeaderToggleButton.tsx
  src/components/layout/home/main/StartButton.tsx
  src/components/layout/home/styles/Home.module.css
  src/pages/_app.tsx
Labels: 🐛 버그, 🎨 디자인 수정, 🪚 리팩토링

#411 💄 style: 메뉴 모달, Magin Modal Confirm 사이즈 수정 피그마대로 적용 (#286)
  public/icons/exclamation-mark.svg
  src/components/menu-category/CategroyCard.tsx
  src/components/menu-category/modal/MenuCategoryModal.tsx
  src/components/menu-category/styles/modal.module.css
  src/components/menu-item/MenuItemContainer.tsx
  src/components/menu-item/items/MenuItemFormButton.tsx
  src/components/menu-item/items/MenuItemModal.tsx
  src/components/menu-item/options/MenuItemFormOption.tsx
  src/components/menu-item/options/MenuOptionModal.tsx
  src/components/menu-item/styles/menu-item-card.module.css
  src/components/menu-item/styles/menu-item-container.module.css
  src/components/menu-item/styles/menu-item-form.module.css
  src/components/menu-item/styles/modal.module.css
  src/components/modal/default/ConfirmModal.tsx
  src/components/modal/default/styles/ConfirmModal.module.css
  src/components/modal/styles/Modal.module.css
  src/components/table/TableListItem.tsx
Labels: 🎨 디자인 수정

#416 🩹 fix: 이메일 포커스 될 때도 Enter 기능 수행 (#415)
  src/components/auth/Input.tsx
Labels: 📝 기능 수정

#438 💄 style: 로그인/회원가입 시안 수정
  src/components/auth/AuthForm.tsx
  src/components/auth/styles/Auth.module.css
  src/data/auth.ts
  src/data/input-props.ts
  src/styles/globals.css
Labels: 🎨 디자인 수정
